<?php
//
// File generated by Dolibarr installer 22.0.4 on Feb 16, 2026
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='https://www.moulaty.net';
$dolibarr_main_document_root="/home/zemo2264/public_html";
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt="/home/zemo2264/public_html/custom";
$dolibarr_main_data_root="/home/zemo2264/dolibarrdata1234";
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='0';

$dolibarr_main_db_name='zemo2264_base_moulaty2105';
//$dolibarr_main_db_name='zemo2264_doli204';
//$dolibarr_main_db_name='zemo2264_doli287';
//$dolibarr_main_db_prefix='llxve_';
$dolibarr_main_db_prefix='llxve_';
$dolibarr_main_db_user='zemo2264_MOULATY';
$dolibarr_main_db_pass='123azeQSD&é"';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_general_ci';
// Authentication settings
$dolibarr_main_authentication='dolibarr';

//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod='0';
$dolibarr_main_force_https='0';
$dolibarr_main_restrict_os_commands='mariadb-dump, mariadb, mysqldump, mysql, pg_dump, pg_restore, clamdscan, clamdscan.exe';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_instance_unique_id='79a831e8358dd5c5f621ce5918ed0721';
$dolibarr_mailing_limit_sendbyweb='0';
$dolibarr_mailing_limit_sendbycli='0';

//$dolibarr_lib_FPDF_PATH="";
//$dolibarr_lib_TCPDF_PATH="";
//$dolibarr_lib_FPDI_PATH="";
//$dolibarr_lib_TCPDI_PATH="";
//$dolibarr_lib_GEOIP_PATH="";
//$dolibarr_lib_NUSOAP_PATH="";
//$dolibarr_lib_ODTPHP_PATH="";
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP="";
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
$dolibarr_main_distrib='standard';
